[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
counter = "35PUHEFrHabVCwCCNnbEKFXQRn6MquzRkC7jT3ktg7uG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
